import serial
import time
import csv
import matplotlib.pyplot as plt

"""
PID Logging and Plotting Script

Important Disclaimer: I did not author this code. This script was generated by AI. I think it's important to be transparent about use in my work.
Primary AI used: ChatGPT (OpenAI).

The script is used as a tooling aid for logging and visualizing my embedded system telemetry data.

"""

# ==== USER SETTINGS ====
# PORT = 'COM3'          # Windows: COM3, COM4, etc.
# PORT = '/dev/ttyUSB0'  # Linux
PORT = '/dev/tty.usbserial-BG02BZYT'  # Mac
BAUD = 115200
DURATION = 60          # seconds to log
OUTPUT_FILE = "pid_disturbance_test_lower.csv" # change 
#pid_disturbance_test
# =======================

print("Connecting to serial...")
ser = serial.Serial(PORT, BAUD, timeout=1)
time.sleep(2)  # allow Arduino to reset

print("Logging data...")
start_time = time.time()

data = []

with open(OUTPUT_FILE, 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["time_ms", "rpm", "pwm"])

    while time.time() - start_time < DURATION:
        line = ser.readline().decode('utf-8').strip()
        if line:
            try:
                t, rpm, pwm = line.split(',')
                writer.writerow([t, rpm, pwm])
                data.append((int(t), float(rpm), int(pwm)))
            except:
                pass

ser.close()
print(f"Saved to {OUTPUT_FILE}")

# ==== Plotting ====
if data:
    times = [(row[0] - data[0][0]) / 1000.0 for row in data]  # seconds
    rpms = [row[1] for row in data]
    pwms = [row[2] for row in data]

    plt.figure()
    plt.plot(times, rpms, label="RPM")
    plt.axhline(150, linestyle='--', label="Setpoint")
    plt.xlabel("Time (s)")
    plt.ylabel("RPM")
    plt.title("PID Step Response")
    plt.legend()
    plt.grid()

    plt.figure()
    plt.plot(times, pwms, label="PWM")
    plt.xlabel("Time (s)")
    plt.ylabel("PWM")
    plt.title("PWM Output")
    plt.legend()
    plt.grid()

    plt.show()
else:
    print("No data collected.")
